version: "3.8"

services:
  mongo_db:
    image: mongo
    ports:
      - 27017:27017

  postgres_db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data: